version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./nginx/lift.jantimpe.com:/etc/nginx/sites-enabled/default
      - ./build:/var/www/html
      - /etc/letsencrypt/copy/lift.jantimpe.com:/etc/letsencrypt/lift.jantimpe.com
    depends_on:
      - react

  react:
    command: yarn build
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules