version: '3'

services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000